
# 使用 PyTorch 进行深度学习：60 分钟的闪电战
在这里我们会完成：
- 全面了解 PyTorch 的 Tensor 库和神经网络
- 训练一个小的神经网络对图像进行分类



## 什么是 PyTorch
这是一个深度学习框架，作为 Numpy 的替代品，可以利用 gpu 的性能进行计算

具有高灵活，速度快的特性

### 张量
这个是 PyTorch 中最基本的概念，类似 Numpy 的 ndarray，并且可以使用 gpu 进行加速计算,这也是他和 `ndarray` 的区别。

In [2]:
from __future__ import print_function
import torch
import numpy as np

#### 张量的初始化
张量的有多种初始化方式：
1. 直接生成张量
2. 使用 numpy 数组来生成张量（当然反过来也可以）
3. 通过已有的张量来生成新的张量
4. 指定数据的维度来生成张量

In [3]:
# 直接生成张量
data = [[1,2],[3,4]]
x_data=torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# 使用 numpy 数组
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [5]:
# 通过已有张量生成新张量
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_rand=torch.rand_like(x_data,dtype=torch.float)    # 可以重写其数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7146, 0.3678],
        [0.6441, 0.9313]]) 



In [6]:
# 指定数据维度来生成张量（最常用）
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.0937, 0.6008, 0.2880],
        [0.7255, 0.6514, 0.0158]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### 张量属性
张量属性中包含有张量的特征，有：
- 张量的维数
- 数据类型
- 所在的存储设备

In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


#### 张量运算
张量运算实在是太多了，有例如转置，索引，切片，数学运算，线性代数，随机采样等，大部分 Numpy 数组能做的运算张量也是可以做的
这些运算都可以在 GPU 上运行！

In [9]:
# 判断当前环境GPU是否可用, 然后将tensor导入GPU内运行
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
tensor.device

device(type='cpu')

接下来我们来看些例子，熟悉 Numpy 的话将会感觉挺熟悉
1. 张量的索引和切片

In [10]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0            # 将第1列(从0开始)的数据全部赋值为0
print(tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


2. 张量的拼接

我们可以使用 `torch.cat` 的方法将一组张量按照指定的维度进行拼接，或者是使用 `torch.stack` 方法，这两个有稍微不同

`torch.cat` 方法是直接连接，不会**新增加**维度
`torch.stack` 方法会新增加维度，并在这个新增加维度内进行连接

In [20]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.stack([tensor,tensor,tensor],dim=1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


3. 张量乘积以及矩阵乘法

张量直接可以进行运算，运算有元素级的和矩阵级别的

In [21]:
# 逐个元素相乘结果
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
# 等价写法:
print(f"tensor * tensor: \n {tensor * tensor}")


tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


如果像下面这样写就是矩阵乘法，当然这个 `@` 运算符好像是新的，比较少用到

In [22]:
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")
# 等价写法:
print(f"tensor @ tensor.T: \n {tensor @ tensor.T}")


tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


4. 自动赋值运算

一般来说，调用 Tensor 的方法，如果有 `_` 作为后缀，那么这个操作将会改变其本身的值，否则不会

In [25]:
print(tensor, "\n")
tensor.add(5)
print(tensor)
tensor.add_(5)
print(tensor)


tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])
tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


> 注意：
> 自动赋值运算虽然可以节省内存，但是在**求导**的时候会因为丢失了中间过程而带来问题，不鼓励使用

#### Tensor 和 Numpy 的转化
事实上，二者可以共享同一块内存区域，也就是说，其中一个改变了，另一个也会随之改变，我们来看例子
1. 张量变成 Numpy 数组

In [27]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


如果修改了其中一个的值，另一个也会改变

In [28]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


反过来，把 Numpy 数组转化成张量，并修改其值

In [30]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## `torch.autograd` 的简要介绍
这是 Pytorch 的自动差分引擎，可以对神经网络的训练提供支持